### ISSUE TITLE
Remove extraneous files from repos.

### ISSUE THREAD

**Issue by clegoues** [mausotog/ProbModelPaper#1]
Please remove the .log, .aux, .pdf, and other byproducts of build from this repos, along with the IEEE howto PDF.  Note that this, and other similar principles for collaborating, are covered in my writing guide (https://clairelegoues.com/2016/08/23/things-i-keep-repeating-about-writing/).

Then add them to a .gitignore and push it.

Also, please rename your main .tex such that it is indicative.

**Comment by mausotog** [comment]
Done
